name: backend

on: 
  push:
    branches: [ main ]

jobs:
  job_1:
    name: build image and push to dockerhub
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: build image
        working-directory: DevOps-Labs-Backend
        run: docker build . --file Dockerfile --tag dotnet_backend_application:$(git rev-parse --short "$GITHUB_SHA")

