name: backend

on: 
  push:
    branches: [ main ]

env:
  COMMIT_ID: ${{ github.sha }}

jobs:
  job_1:
    name: build image and push to dockerhub
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: build image
        run: docker build . --file DevOps-Labs-Backend/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/dotnet_backend_application:${COMMIT_ID:0:6}
      
      - name: push to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dotnet_backend_application:${COMMIT_ID:0:6}
      
  job_2:
    name: deploy the image localy
    needs: job_1
    runs-on: ubuntu-latest
    steps:

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }} 
          port: 22
          script: |
            cd /home/ubuntu/CICD/devops-labs-dotnet-backend 
            ./script.sh ${COMMIT_ID:0:6}


